name: dtubeapp
description: Stream Dube content.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^6.0.0
  dio: ^0.0.13
  simple_moment: ^0.0.3
  url_launcher: ^3.0.1
  shared_preferences: ^0.4.1
  screen: ^0.0.3
  open_iconic_flutter: ">=0.2.0 <0.3.0"
  html: any
  uni_links: "^0.1.1"
  flutter_custom_tabs: ^0.2.0
  cached_network_image: ^0.4.1
  firebase_admob: ^0.5.5
  firebase_analytics: ^1.0.1
  video_launcher: "^0.3.0"
  video_player: ^0.6.4
  flutter_billing: "^0.2.2"
  chewie: ^0.6.1
  package_info: ^0.3.2
  share: "^0.5.2"
  flutter_android_pip: ^0.0.2
  carousel_slider: "^0.0.6"
  flutter_local_notifications: "^0.3.5"
  permissions: "^0.1.2"
  open_file: "^1.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/video_placeholder.png
   - assets/web_hi_res_512.png
   - assets/DTube_Black.png
   - assets/DTube_White.png
   - "assets/screenshot (1).jpg"
   - "assets/screenshot (2).jpg"
   - "assets/screenshot (3).jpg"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
